# Generated by Django 4.2.2 on 2023-06-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tastyapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation',
            field=models.TextField(max_length=3000, null=True),
        ),
    ]
