# Generated by Django 4.2.2 on 2023-06-12 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tastyapi', '0003_alter_recipe_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='comments',
        ),
        migrations.DeleteModel(
            name='RecipeComment',
        ),
    ]
