# Generated by Django 4.2.2 on 2023-06-20 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tastyapi', '0006_alter_comment_recipe_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='tastyapi.recipe'),
        ),
    ]
